//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaServiex.SrvRef_CRUD_Serviex {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WcfPruebaServiex")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvRef_CRUD_Serviex.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPersonas", ReplyAction="http://tempuri.org/IService1/ObtenerPersonasResponse")]
        PSModel.Entidades.Persona[] ObtenerPersonas(System.Nullable<int> id_persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPersona", ReplyAction="http://tempuri.org/IService1/InsertarPersonaResponse")]
        int InsertarPersona(PSModel.Entidades.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarPersona", ReplyAction="http://tempuri.org/IService1/EditarPersonaResponse")]
        bool EditarPersona(PSModel.Entidades.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPersona", ReplyAction="http://tempuri.org/IService1/EliminarPersonaResponse")]
        string EliminarPersona(int id_persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPersonasPD", ReplyAction="http://tempuri.org/IService1/ObtenerPersonasPDResponse")]
        PruebaServiex.SrvRef_CRUD_Serviex.Persona[] ObtenerPersonasPD(System.Nullable<int> id_persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPersonaPD", ReplyAction="http://tempuri.org/IService1/InsertarPersonaPDResponse")]
        int InsertarPersonaPD(PruebaServiex.SrvRef_CRUD_Serviex.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarPersonaPD", ReplyAction="http://tempuri.org/IService1/EditarPersonaPDResponse")]
        bool EditarPersonaPD(PruebaServiex.SrvRef_CRUD_Serviex.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPersonaPD", ReplyAction="http://tempuri.org/IService1/EliminarPersonaPDResponse")]
        string EliminarPersonaPD(int id_persona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PruebaServiex.SrvRef_CRUD_Serviex.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PruebaServiex.SrvRef_CRUD_Serviex.IService1>, PruebaServiex.SrvRef_CRUD_Serviex.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PSModel.Entidades.Persona[] ObtenerPersonas(System.Nullable<int> id_persona) {
            return base.Channel.ObtenerPersonas(id_persona);
        }
        
        public int InsertarPersona(PSModel.Entidades.Persona p) {
            return base.Channel.InsertarPersona(p);
        }
        
        public bool EditarPersona(PSModel.Entidades.Persona p) {
            return base.Channel.EditarPersona(p);
        }
        
        public string EliminarPersona(int id_persona) {
            return base.Channel.EliminarPersona(id_persona);
        }
        
        public PruebaServiex.SrvRef_CRUD_Serviex.Persona[] ObtenerPersonasPD(System.Nullable<int> id_persona) {
            return base.Channel.ObtenerPersonasPD(id_persona);
        }
        
        public int InsertarPersonaPD(PruebaServiex.SrvRef_CRUD_Serviex.Persona p) {
            return base.Channel.InsertarPersonaPD(p);
        }
        
        public bool EditarPersonaPD(PruebaServiex.SrvRef_CRUD_Serviex.Persona p) {
            return base.Channel.EditarPersonaPD(p);
        }
        
        public string EliminarPersonaPD(int id_persona) {
            return base.Channel.EliminarPersonaPD(id_persona);
        }
    }
}
